package ca.joaoborges.filemanager.operations.common;

public interface OperationConstants {

    String RENAME_OPERATION = "RENAME_OPERATION";
    String ORGANIZATION_OPERATION = "ORGANIZATION_OPERATION";
    String EXTRACTION_OPERATION = "EXTRACTION_OPERATION";
    String PHOTO_ORGANIZATION_OPERATION = "PHOTO_ORGANIZATION_OPERATION";
    String DUPLICATE_FINDER_OPERATION = "DUPLICATE_FINDER_OPERATION";

}
